#Exception是所有程序异常类的 父类。
try:
    print(1 / 0)
    print(num)

except Exception as result:
    print(result)